// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=../../mocks/mock_usecase_server.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	entity "github.com/llravell/go-pass/internal/entity"
	server "github.com/llravell/go-pass/internal/usecase/server"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// FindUserByLogin mocks base method.
func (m *MockUserRepository) FindUserByLogin(ctx context.Context, login string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByLogin", ctx, login)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByLogin indicates an expected call of FindUserByLogin.
func (mr *MockUserRepositoryMockRecorder) FindUserByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByLogin", reflect.TypeOf((*MockUserRepository)(nil).FindUserByLogin), ctx, login)
}

// StoreUser mocks base method.
func (m *MockUserRepository) StoreUser(ctx context.Context, login, password string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreUser", ctx, login, password)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreUser indicates an expected call of StoreUser.
func (mr *MockUserRepositoryMockRecorder) StoreUser(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreUser", reflect.TypeOf((*MockUserRepository)(nil).StoreUser), ctx, login, password)
}

// MockPasswordsRepository is a mock of PasswordsRepository interface.
type MockPasswordsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordsRepositoryMockRecorder
	isgomock struct{}
}

// MockPasswordsRepositoryMockRecorder is the mock recorder for MockPasswordsRepository.
type MockPasswordsRepositoryMockRecorder struct {
	mock *MockPasswordsRepository
}

// NewMockPasswordsRepository creates a new mock instance.
func NewMockPasswordsRepository(ctrl *gomock.Controller) *MockPasswordsRepository {
	mock := &MockPasswordsRepository{ctrl: ctrl}
	mock.recorder = &MockPasswordsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordsRepository) EXPECT() *MockPasswordsRepositoryMockRecorder {
	return m.recorder
}

// AddNewPassword mocks base method.
func (m *MockPasswordsRepository) AddNewPassword(ctx context.Context, userID int, password *entity.Password) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewPassword", ctx, userID, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNewPassword indicates an expected call of AddNewPassword.
func (mr *MockPasswordsRepositoryMockRecorder) AddNewPassword(ctx, userID, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewPassword", reflect.TypeOf((*MockPasswordsRepository)(nil).AddNewPassword), ctx, userID, password)
}

// DeletePasswordByName mocks base method.
func (m *MockPasswordsRepository) DeletePasswordByName(ctx context.Context, userID int, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePasswordByName", ctx, userID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePasswordByName indicates an expected call of DeletePasswordByName.
func (mr *MockPasswordsRepositoryMockRecorder) DeletePasswordByName(ctx, userID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePasswordByName", reflect.TypeOf((*MockPasswordsRepository)(nil).DeletePasswordByName), ctx, userID, name)
}

// GetPasswords mocks base method.
func (m *MockPasswordsRepository) GetPasswords(ctx context.Context, userID int) ([]*entity.Password, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswords", ctx, userID)
	ret0, _ := ret[0].([]*entity.Password)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswords indicates an expected call of GetPasswords.
func (mr *MockPasswordsRepositoryMockRecorder) GetPasswords(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswords", reflect.TypeOf((*MockPasswordsRepository)(nil).GetPasswords), ctx, userID)
}

// UpdateByName mocks base method.
func (m *MockPasswordsRepository) UpdateByName(ctx context.Context, userID int, name string, updateFn func(*entity.Password) (*entity.Password, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByName", ctx, userID, name, updateFn)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByName indicates an expected call of UpdateByName.
func (mr *MockPasswordsRepositoryMockRecorder) UpdateByName(ctx, userID, name, updateFn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByName", reflect.TypeOf((*MockPasswordsRepository)(nil).UpdateByName), ctx, userID, name, updateFn)
}

// MockCardsRepository is a mock of CardsRepository interface.
type MockCardsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCardsRepositoryMockRecorder
	isgomock struct{}
}

// MockCardsRepositoryMockRecorder is the mock recorder for MockCardsRepository.
type MockCardsRepositoryMockRecorder struct {
	mock *MockCardsRepository
}

// NewMockCardsRepository creates a new mock instance.
func NewMockCardsRepository(ctrl *gomock.Controller) *MockCardsRepository {
	mock := &MockCardsRepository{ctrl: ctrl}
	mock.recorder = &MockCardsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardsRepository) EXPECT() *MockCardsRepositoryMockRecorder {
	return m.recorder
}

// AddNewCard mocks base method.
func (m *MockCardsRepository) AddNewCard(ctx context.Context, userID int, card *entity.Card) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewCard", ctx, userID, card)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNewCard indicates an expected call of AddNewCard.
func (mr *MockCardsRepositoryMockRecorder) AddNewCard(ctx, userID, card any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewCard", reflect.TypeOf((*MockCardsRepository)(nil).AddNewCard), ctx, userID, card)
}

// DeleteCardByName mocks base method.
func (m *MockCardsRepository) DeleteCardByName(ctx context.Context, userID int, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCardByName", ctx, userID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCardByName indicates an expected call of DeleteCardByName.
func (mr *MockCardsRepositoryMockRecorder) DeleteCardByName(ctx, userID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCardByName", reflect.TypeOf((*MockCardsRepository)(nil).DeleteCardByName), ctx, userID, name)
}

// GetCards mocks base method.
func (m *MockCardsRepository) GetCards(ctx context.Context, userID int) ([]*entity.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCards", ctx, userID)
	ret0, _ := ret[0].([]*entity.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCards indicates an expected call of GetCards.
func (mr *MockCardsRepositoryMockRecorder) GetCards(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCards", reflect.TypeOf((*MockCardsRepository)(nil).GetCards), ctx, userID)
}

// UpdateByName mocks base method.
func (m *MockCardsRepository) UpdateByName(ctx context.Context, userID int, name string, updateFn func(*entity.Card) (*entity.Card, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByName", ctx, userID, name, updateFn)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByName indicates an expected call of UpdateByName.
func (mr *MockCardsRepositoryMockRecorder) UpdateByName(ctx, userID, name, updateFn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByName", reflect.TypeOf((*MockCardsRepository)(nil).UpdateByName), ctx, userID, name, updateFn)
}

// MockFilesRepository is a mock of FilesRepository interface.
type MockFilesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFilesRepositoryMockRecorder
	isgomock struct{}
}

// MockFilesRepositoryMockRecorder is the mock recorder for MockFilesRepository.
type MockFilesRepositoryMockRecorder struct {
	mock *MockFilesRepository
}

// NewMockFilesRepository creates a new mock instance.
func NewMockFilesRepository(ctrl *gomock.Controller) *MockFilesRepository {
	mock := &MockFilesRepository{ctrl: ctrl}
	mock.recorder = &MockFilesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilesRepository) EXPECT() *MockFilesRepositoryMockRecorder {
	return m.recorder
}

// DeleteFileByName mocks base method.
func (m *MockFilesRepository) DeleteFileByName(ctx context.Context, userID int, bucket, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFileByName", ctx, userID, bucket, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFileByName indicates an expected call of DeleteFileByName.
func (mr *MockFilesRepositoryMockRecorder) DeleteFileByName(ctx, userID, bucket, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFileByName", reflect.TypeOf((*MockFilesRepository)(nil).DeleteFileByName), ctx, userID, bucket, name)
}

// GetFileByName mocks base method.
func (m *MockFilesRepository) GetFileByName(ctx context.Context, userID int, bucket, name string) (*entity.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileByName", ctx, userID, bucket, name)
	ret0, _ := ret[0].(*entity.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileByName indicates an expected call of GetFileByName.
func (mr *MockFilesRepositoryMockRecorder) GetFileByName(ctx, userID, bucket, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileByName", reflect.TypeOf((*MockFilesRepository)(nil).GetFileByName), ctx, userID, bucket, name)
}

// GetFiles mocks base method.
func (m *MockFilesRepository) GetFiles(ctx context.Context, userID int, bucket string) ([]*entity.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFiles", ctx, userID, bucket)
	ret0, _ := ret[0].([]*entity.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFiles indicates an expected call of GetFiles.
func (mr *MockFilesRepositoryMockRecorder) GetFiles(ctx, userID, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFiles", reflect.TypeOf((*MockFilesRepository)(nil).GetFiles), ctx, userID, bucket)
}

// UploadFile mocks base method.
func (m *MockFilesRepository) UploadFile(ctx context.Context, userID int, file *entity.File, uploadFn func() (int64, error), deleteFn func() error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, userID, file, uploadFn, deleteFn)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockFilesRepositoryMockRecorder) UploadFile(ctx, userID, file, uploadFn, deleteFn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockFilesRepository)(nil).UploadFile), ctx, userID, file, uploadFn, deleteFn)
}

// MockFilesS3Storage is a mock of FilesS3Storage interface.
type MockFilesS3Storage struct {
	ctrl     *gomock.Controller
	recorder *MockFilesS3StorageMockRecorder
	isgomock struct{}
}

// MockFilesS3StorageMockRecorder is the mock recorder for MockFilesS3Storage.
type MockFilesS3StorageMockRecorder struct {
	mock *MockFilesS3Storage
}

// NewMockFilesS3Storage creates a new mock instance.
func NewMockFilesS3Storage(ctrl *gomock.Controller) *MockFilesS3Storage {
	mock := &MockFilesS3Storage{ctrl: ctrl}
	mock.recorder = &MockFilesS3StorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilesS3Storage) EXPECT() *MockFilesS3StorageMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockFilesS3Storage) DeleteFile(ctx context.Context, file *entity.File) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFilesS3StorageMockRecorder) DeleteFile(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFilesS3Storage)(nil).DeleteFile), ctx, file)
}

// DownloadFile mocks base method.
func (m *MockFilesS3Storage) DownloadFile(ctx context.Context, file *entity.File) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", ctx, file)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockFilesS3StorageMockRecorder) DownloadFile(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockFilesS3Storage)(nil).DownloadFile), ctx, file)
}

// UploadFile mocks base method.
func (m *MockFilesS3Storage) UploadFile(ctx context.Context, file *entity.File, fileReader io.Reader) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, file, fileReader)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockFilesS3StorageMockRecorder) UploadFile(ctx, file, fileReader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockFilesS3Storage)(nil).UploadFile), ctx, file, fileReader)
}

// MockFileDeletingWorkerPool is a mock of FileDeletingWorkerPool interface.
type MockFileDeletingWorkerPool struct {
	ctrl     *gomock.Controller
	recorder *MockFileDeletingWorkerPoolMockRecorder
	isgomock struct{}
}

// MockFileDeletingWorkerPoolMockRecorder is the mock recorder for MockFileDeletingWorkerPool.
type MockFileDeletingWorkerPoolMockRecorder struct {
	mock *MockFileDeletingWorkerPool
}

// NewMockFileDeletingWorkerPool creates a new mock instance.
func NewMockFileDeletingWorkerPool(ctrl *gomock.Controller) *MockFileDeletingWorkerPool {
	mock := &MockFileDeletingWorkerPool{ctrl: ctrl}
	mock.recorder = &MockFileDeletingWorkerPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileDeletingWorkerPool) EXPECT() *MockFileDeletingWorkerPoolMockRecorder {
	return m.recorder
}

// QueueWork mocks base method.
func (m *MockFileDeletingWorkerPool) QueueWork(w *server.FileDeleteWork) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueWork", w)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueWork indicates an expected call of QueueWork.
func (mr *MockFileDeletingWorkerPoolMockRecorder) QueueWork(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueWork", reflect.TypeOf((*MockFileDeletingWorkerPool)(nil).QueueWork), w)
}

// MockJWTIssuer is a mock of JWTIssuer interface.
type MockJWTIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockJWTIssuerMockRecorder
	isgomock struct{}
}

// MockJWTIssuerMockRecorder is the mock recorder for MockJWTIssuer.
type MockJWTIssuerMockRecorder struct {
	mock *MockJWTIssuer
}

// NewMockJWTIssuer creates a new mock instance.
func NewMockJWTIssuer(ctrl *gomock.Controller) *MockJWTIssuer {
	mock := &MockJWTIssuer{ctrl: ctrl}
	mock.recorder = &MockJWTIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTIssuer) EXPECT() *MockJWTIssuerMockRecorder {
	return m.recorder
}

// Issue mocks base method.
func (m *MockJWTIssuer) Issue(userID int, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue", userID, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Issue indicates an expected call of Issue.
func (mr *MockJWTIssuerMockRecorder) Issue(userID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockJWTIssuer)(nil).Issue), userID, ttl)
}
