// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: api/conflict.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConflictType int32

const (
	ConflictType_DIFF    ConflictType = 0
	ConflictType_DELETED ConflictType = 1
)

// Enum value maps for ConflictType.
var (
	ConflictType_name = map[int32]string{
		0: "DIFF",
		1: "DELETED",
	}
	ConflictType_value = map[string]int32{
		"DIFF":    0,
		"DELETED": 1,
	}
)

func (x ConflictType) Enum() *ConflictType {
	p := new(ConflictType)
	*p = x
	return p
}

func (x ConflictType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConflictType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_conflict_proto_enumTypes[0].Descriptor()
}

func (ConflictType) Type() protoreflect.EnumType {
	return &file_api_conflict_proto_enumTypes[0]
}

func (x ConflictType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConflictType.Descriptor instead.
func (ConflictType) EnumDescriptor() ([]byte, []int) {
	return file_api_conflict_proto_rawDescGZIP(), []int{0}
}

var File_api_conflict_proto protoreflect.FileDescriptor

var file_api_conflict_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x6c, 0x69, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x6c, 0x69,
	0x63, 0x74, 0x2a, 0x25, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x66, 0x6c, 0x69, 0x63, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x49, 0x46, 0x46, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x6b, 0x67,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_api_conflict_proto_rawDescOnce sync.Once
	file_api_conflict_proto_rawDescData []byte
)

func file_api_conflict_proto_rawDescGZIP() []byte {
	file_api_conflict_proto_rawDescOnce.Do(func() {
		file_api_conflict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_conflict_proto_rawDesc), len(file_api_conflict_proto_rawDesc)))
	})
	return file_api_conflict_proto_rawDescData
}

var file_api_conflict_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_conflict_proto_goTypes = []any{
	(ConflictType)(0), // 0: api.conflict.ConflictType
}
var file_api_conflict_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_conflict_proto_init() }
func file_api_conflict_proto_init() {
	if File_api_conflict_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_conflict_proto_rawDesc), len(file_api_conflict_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_conflict_proto_goTypes,
		DependencyIndexes: file_api_conflict_proto_depIdxs,
		EnumInfos:         file_api_conflict_proto_enumTypes,
	}.Build()
	File_api_conflict_proto = out.File
	file_api_conflict_proto_goTypes = nil
	file_api_conflict_proto_depIdxs = nil
}
