// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: api/notes.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotesGetListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notes         []*FileInfo            `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotesGetListResponse) Reset() {
	*x = NotesGetListResponse{}
	mi := &file_api_notes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotesGetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotesGetListResponse) ProtoMessage() {}

func (x *NotesGetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotesGetListResponse.ProtoReflect.Descriptor instead.
func (*NotesGetListResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_proto_rawDescGZIP(), []int{0}
}

func (x *NotesGetListResponse) GetNotes() []*FileInfo {
	if x != nil {
		return x.Notes
	}
	return nil
}

type NotesUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotesUploadResponse) Reset() {
	*x = NotesUploadResponse{}
	mi := &file_api_notes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotesUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotesUploadResponse) ProtoMessage() {}

func (x *NotesUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotesUploadResponse.ProtoReflect.Descriptor instead.
func (*NotesUploadResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_proto_rawDescGZIP(), []int{1}
}

func (x *NotesUploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type NotesDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotesDownloadRequest) Reset() {
	*x = NotesDownloadRequest{}
	mi := &file_api_notes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotesDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotesDownloadRequest) ProtoMessage() {}

func (x *NotesDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotesDownloadRequest.ProtoReflect.Descriptor instead.
func (*NotesDownloadRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_proto_rawDescGZIP(), []int{2}
}

func (x *NotesDownloadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NotesDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotesDeleteRequest) Reset() {
	*x = NotesDeleteRequest{}
	mi := &file_api_notes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotesDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotesDeleteRequest) ProtoMessage() {}

func (x *NotesDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotesDeleteRequest.ProtoReflect.Descriptor instead.
func (*NotesDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_proto_rawDescGZIP(), []int{3}
}

func (x *NotesDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_notes_proto protoreflect.FileDescriptor

var file_api_notes_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x66,
	0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x14, 0x4e, 0x6f, 0x74,
	0x65, 0x73, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x28, 0x0a, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x2f, 0x0a, 0x13, 0x4e,
	0x6f, 0x74, 0x65, 0x73, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2a, 0x0a, 0x14,
	0x4e, 0x6f, 0x74, 0x65, 0x73, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x4e, 0x6f, 0x74, 0x65,
	0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x32, 0x91, 0x02, 0x0a, 0x05, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x42, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x4e, 0x6f, 0x74, 0x65,
	0x73, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3f, 0x0a, 0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x13, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x1a,
	0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x4e, 0x6f, 0x74, 0x65,
	0x73, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28,
	0x01, 0x12, 0x42, 0x0a, 0x08, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1f, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x30, 0x01, 0x12, 0x3f, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x4e, 0x6f, 0x74, 0x65,
	0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_api_notes_proto_rawDescOnce sync.Once
	file_api_notes_proto_rawDescData []byte
)

func file_api_notes_proto_rawDescGZIP() []byte {
	file_api_notes_proto_rawDescOnce.Do(func() {
		file_api_notes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_notes_proto_rawDesc), len(file_api_notes_proto_rawDesc)))
	})
	return file_api_notes_proto_rawDescData
}

var file_api_notes_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_notes_proto_goTypes = []any{
	(*NotesGetListResponse)(nil), // 0: api.notes.NotesGetListResponse
	(*NotesUploadResponse)(nil),  // 1: api.notes.NotesUploadResponse
	(*NotesDownloadRequest)(nil), // 2: api.notes.NotesDownloadRequest
	(*NotesDeleteRequest)(nil),   // 3: api.notes.NotesDeleteRequest
	(*FileInfo)(nil),             // 4: api.file.FileInfo
	(*emptypb.Empty)(nil),        // 5: google.protobuf.Empty
	(*FileChunk)(nil),            // 6: api.file.FileChunk
}
var file_api_notes_proto_depIdxs = []int32{
	4, // 0: api.notes.NotesGetListResponse.notes:type_name -> api.file.FileInfo
	5, // 1: api.notes.Notes.GetList:input_type -> google.protobuf.Empty
	6, // 2: api.notes.Notes.Upload:input_type -> api.file.FileChunk
	2, // 3: api.notes.Notes.Download:input_type -> api.notes.NotesDownloadRequest
	3, // 4: api.notes.Notes.Delete:input_type -> api.notes.NotesDeleteRequest
	0, // 5: api.notes.Notes.GetList:output_type -> api.notes.NotesGetListResponse
	1, // 6: api.notes.Notes.Upload:output_type -> api.notes.NotesUploadResponse
	6, // 7: api.notes.Notes.Download:output_type -> api.file.FileChunk
	5, // 8: api.notes.Notes.Delete:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_notes_proto_init() }
func file_api_notes_proto_init() {
	if File_api_notes_proto != nil {
		return
	}
	file_api_file_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notes_proto_rawDesc), len(file_api_notes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_notes_proto_goTypes,
		DependencyIndexes: file_api_notes_proto_depIdxs,
		MessageInfos:      file_api_notes_proto_msgTypes,
	}.Build()
	File_api_notes_proto = out.File
	file_api_notes_proto_goTypes = nil
	file_api_notes_proto_depIdxs = nil
}
