// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/passwords.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Passwords_Sync_FullMethodName = "/passwords.Passwords/Sync"
)

// PasswordsClient is the client API for Passwords service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PasswordsClient interface {
	Sync(ctx context.Context, in *Password, opts ...grpc.CallOption) (*SyncResponse, error)
}

type passwordsClient struct {
	cc grpc.ClientConnInterface
}

func NewPasswordsClient(cc grpc.ClientConnInterface) PasswordsClient {
	return &passwordsClient{cc}
}

func (c *passwordsClient) Sync(ctx context.Context, in *Password, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, Passwords_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PasswordsServer is the server API for Passwords service.
// All implementations must embed UnimplementedPasswordsServer
// for forward compatibility.
type PasswordsServer interface {
	Sync(context.Context, *Password) (*SyncResponse, error)
	mustEmbedUnimplementedPasswordsServer()
}

// UnimplementedPasswordsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPasswordsServer struct{}

func (UnimplementedPasswordsServer) Sync(context.Context, *Password) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedPasswordsServer) mustEmbedUnimplementedPasswordsServer() {}
func (UnimplementedPasswordsServer) testEmbeddedByValue()                   {}

// UnsafePasswordsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PasswordsServer will
// result in compilation errors.
type UnsafePasswordsServer interface {
	mustEmbedUnimplementedPasswordsServer()
}

func RegisterPasswordsServer(s grpc.ServiceRegistrar, srv PasswordsServer) {
	// If the following call pancis, it indicates UnimplementedPasswordsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Passwords_ServiceDesc, srv)
}

func _Passwords_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Password)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordsServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Passwords_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordsServer).Sync(ctx, req.(*Password))
	}
	return interceptor(ctx, in, info, handler)
}

// Passwords_ServiceDesc is the grpc.ServiceDesc for Passwords service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Passwords_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "passwords.Passwords",
	HandlerType: (*PasswordsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _Passwords_Sync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/passwords.proto",
}
